// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qbmhgupkrashdagluvhj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFibWhndXBrcmFzaGRhZ2x1dmhqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc4NTQ4NTksImV4cCI6MjA3MzQzMDg1OX0.-lkgB7ZqjCnq9tzLNgLja51HIwZ6F8hxwljqd7ZTsgI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});